# Default values for helm foggykitchen hello-world chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# OCI Load Balancer configuration for K8S Service
loadBalancer:
  lbShape: flexible
  lbMinShape: 10
  lbMaxShape: 100
  lbListenerPort: 80

# POD spec
pod:
  numberOfNginxReplicas: 1
  imagePullSecrets: []

# Image 
image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""